run_dir: "./correlation/gnn/measurements/_out"
resume_from_checkpoint: null
schema_path: "C:/git/Clevr-Relational/_clevr_data/_clevr_gnn/clevr_attr_map.json"
attr_names: ["color", "shape", "material", "size"]
output_dims: [8, 3, 2, 2]
batch_size: 16
num_workers: 4
seed: 980413
edge_transformer: "types"
decoder: "random" #" "random" # "results/gnn/clevr/decoder.statedict"

# relevant stuff
input_channels: 15
dataset_dir: "_datasets"
# encoder defined through cmd-line args
# dataset_name defined through cmd-line args
# obj_ann_path defined through cmd-line args
# intermediate_gt defined through cmd-line args
# train_size defined through cmd-line args

#training configuration
num_rels: 4
edge_dim: 4
dropout_p: 0.6
learning_rate: 0.005
max_epochs: 10
val_every_n_epoch: 1
precision: 32
use_sigmoid: True
dev: False
desc: "clevr scenes reconstruction"