run_dir: "./correlation/gnn/_output"
resume_from_checkpoint: null
obj_ann_path: "C:/git/Clevr-Relational/_clevr_gnn/CLEVR_mini_coco_anns.json"
schema_path: "C:/git/Clevr-Relational/_clevr_gnn/clevr_attr_map.json"
attr_names: ["color", "shape", "material", "size"]
output_dims: [8, 3, 2, 2]
batch_size: 1
num_workers: 4
seed: 980413

#training configuration
train_size: 3600
num_rels: 4
edge_dim: 4
dropout_p: 0.6
learning_rate: 0.002
max_epochs: 1
val_every_n_epoch: 1
precision: 32
use_sigmoid: True
dev: False
desc: "clevr scenes reconstruction"